[package]
name = "actix_web_lab"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
env_logger = "0.11.6"
serde = { version = "1.0.217", features = ["derive"] }
futures = "0.3.31"
thiserror = "2.0.11"
